/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import model.Bike;
import model.BikeType;
import model.DB;

/**
 *
 * @author CacTrainer
 */
public class ManageBikesWindow extends javax.swing.JFrame {

    private ArrayList<Bike> bikes;
    private ArrayList<BikeType> bikeTypes;
    
    /**
     * Creates new form ManageBikesWindow
     */
    public ManageBikesWindow() {
        initComponents();
        setLocationRelativeTo(null);
        
        initBikeTypes();
        initBikes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstBikes = new javax.swing.JList<>();
        cmbBikeType = new javax.swing.JComboBox<>();
        lblBikeId = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnDeleteBike = new javax.swing.JButton();
        btnAddNewBike = new javax.swing.JButton();
        cmbBikeColor = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstBikeTypes = new javax.swing.JList<>();
        lblBikeTypeId = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnSaveBikeType = new javax.swing.JButton();
        btnDeleteBikeType = new javax.swing.JButton();
        btnAddNewBikeType = new javax.swing.JButton();
        txtTypeName = new javax.swing.JTextField();
        txtBikeTypePrice = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Manage bikes");
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        lstBikes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstBikes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstBikesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstBikes);

        lblBikeId.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblBikeId.setText("--");

        jLabel2.setText("ID:");

        jLabel3.setText("Bike type:");

        jLabel4.setText("Color:");

        btnSave.setText("Save");

        btnDeleteBike.setText("Delete");

        btnAddNewBike.setText("Add new");

        cmbBikeColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Black", "Blue", "Brown", "Gray", "Green", "Orange", "Pink", "Purple", "Red", "White", "Yellow" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnDeleteBike, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(btnAddNewBike, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblBikeId)
                    .addComponent(btnSave)
                    .addComponent(cmbBikeColor, 0, 95, Short.MAX_VALUE)
                    .addComponent(cmbBikeType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddNewBike))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBikeId)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbBikeType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbBikeColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSave)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeleteBike)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Manage bikes", jPanel1);

        lstBikeTypes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstBikeTypes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstBikeTypesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(lstBikeTypes);

        lblBikeTypeId.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblBikeTypeId.setText("New item");

        jLabel5.setText("ID:");

        jLabel6.setText("Type name:");

        jLabel7.setText("Price:");

        btnSaveBikeType.setText("Save");
        btnSaveBikeType.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaveBikeTypeMouseClicked(evt);
            }
        });

        btnDeleteBikeType.setText("Delete");
        btnDeleteBikeType.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteBikeTypeMouseClicked(evt);
            }
        });

        btnAddNewBikeType.setText("Add new");
        btnAddNewBikeType.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddNewBikeTypeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnDeleteBikeType, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(btnAddNewBikeType, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTypeName)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBikeTypeId)
                            .addComponent(btnSaveBikeType))
                        .addGap(0, 51, Short.MAX_VALUE))
                    .addComponent(txtBikeTypePrice))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddNewBikeType))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBikeTypeId)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtTypeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtBikeTypePrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSaveBikeType)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeleteBikeType)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Manage bike types", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("n");
        jTabbedPane1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lstBikeTypesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstBikeTypesMouseClicked
        
        if(lstBikeTypes.getSelectedValues().length > 0) {
        
            BikeType sBikeType = (BikeType)lstBikeTypes.getSelectedValues()[0];
           
            if(sBikeType != null)
                bikeTypeSelected(sBikeType);
        }
    }//GEN-LAST:event_lstBikeTypesMouseClicked

    private void lstBikesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstBikesMouseClicked
        
        if(lstBikes.getSelectedValues().length > 0) {
        
            Bike sBike = (Bike)lstBikes.getSelectedValues()[0];
           
            if(sBike != null)
                bikeSelected(sBike);
        }
    }//GEN-LAST:event_lstBikesMouseClicked

    private void btnSaveBikeTypeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveBikeTypeMouseClicked
        
        saveBikeType();
    }//GEN-LAST:event_btnSaveBikeTypeMouseClicked

    private void btnAddNewBikeTypeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddNewBikeTypeMouseClicked
        
        clearBikeTypeFields();
    }//GEN-LAST:event_btnAddNewBikeTypeMouseClicked

    private void btnDeleteBikeTypeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteBikeTypeMouseClicked
        
        if(selectedBikeType != null) {
        
            try {
                
                selectedBikeType.delete();
                initBikeTypes();
                clearBikeTypeFields();
            }
            catch(SQLException ex) {
            
                System.out.println("SQLException");
            }
        }
    }//GEN-LAST:event_btnDeleteBikeTypeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageBikesWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageBikesWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageBikesWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageBikesWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageBikesWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNewBike;
    private javax.swing.JButton btnAddNewBikeType;
    private javax.swing.JButton btnDeleteBike;
    private javax.swing.JButton btnDeleteBikeType;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSaveBikeType;
    private javax.swing.JComboBox<String> cmbBikeColor;
    private javax.swing.JComboBox<String> cmbBikeType;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblBikeId;
    private javax.swing.JLabel lblBikeTypeId;
    private javax.swing.JList<String> lstBikeTypes;
    private javax.swing.JList<String> lstBikes;
    private javax.swing.JTextField txtBikeTypePrice;
    private javax.swing.JTextField txtTypeName;
    // End of variables declaration//GEN-END:variables

    private Bike selectedBike = null;
    private BikeType selectedBikeType = null;
    
    private void initBikeTypes() {
    
        try {
        
            bikeTypes = DB.getBikeTypes();
        
            //Load bike types
            DefaultListModel dlmBikeTypes = new DefaultListModel();
            
            for(BikeType b : bikeTypes)
                dlmBikeTypes.addElement(b);
            
            lstBikeTypes.setModel(dlmBikeTypes);
        }
        catch(SQLException ex) {
        
        }
        
    } 
    
    private void initBikes() {
    
        try {
        
            bikes = DB.getAllBikes();
        
            //Load bikes
            DefaultListModel dlmBikes = new DefaultListModel();
            
            for(Bike b : bikes)
                dlmBikes.addElement(b);
            
            lstBikes.setModel(dlmBikes);
        }
        catch(SQLException ex) {
        
        }
        
    } 
    
    private void bikeTypeSelected(BikeType bikeType) {
    
        selectedBikeType = bikeType;
        
        lblBikeTypeId.setText(String.valueOf(bikeType.getId()));
        txtTypeName.setText(bikeType.getTypeName());
        txtBikeTypePrice.setText(String.valueOf(bikeType.getPrice()));
    }
    
    private void bikeSelected(Bike bike) {
    
        selectedBike = bike;
        lblBikeId.setText(String.valueOf(bike.getId()));
    }
    
    private void saveBikeType() {
    
        try {
            if(selectedBikeType == null) {
                BikeType.add(txtTypeName.getText(), 
                             Float.parseFloat(txtBikeTypePrice.getText()));
            }
            else {

                selectedBikeType.setTypeName(txtTypeName.getText(), false);
                selectedBikeType.setPrice(Float.parseFloat(txtBikeTypePrice.getText()), true);
            }
          
            initBikeTypes();
            clearBikeTypeFields();
        }
        catch(SQLException ex) {

            System.out.println("SQLException");
        }
        catch(NumberFormatException ex) {

            System.out.println("NumberFormatException");
        }
    }
    
    private void clearBikeTypeFields() {
    
        selectedBikeType = null;
        lblBikeTypeId.setText("New item");
        txtBikeTypePrice.setText("");
        txtTypeName.setText("");
    }
}
